Sync changes from chameleond
Add bluetooth_grpc service and logrotation, fix Docker warnings, update apt-get commands to pass --yes, change config from btkbservice to btservice as in chameleond, update scripts in init.d to use exec to not spawn separate process and only replace one created by start-stop-daemon, remove binfmt_misc check since qemu-arm-static is not available on Cloudtop and qemu-binfmt used instead

BUG=b:479202587
TEST=./build-docker-cros.sh

Change-Id: I1ba6b2b27f513c4db5ce47d22a5c4948a1a43de1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pi-gen-btpeer/+/7525245
Reviewed-by: Jason Stanko <jstanko@google.com>
Commit-Queue: Alexandr Astrouski <astrouski@google.com>
Tested-by: Alexandr Astrouski <astrouski@google.com>

diff --git a/stage6-btpeer/02-chameleond/rootfs/etc/init.d/bluetooth_grpc b/stage6-btpeer/02-chameleond/rootfs/etc/init.d/bluetooth_grpc
--- a/stage6-btpeer/02-chameleond/rootfs/etc/init.d/bluetooth_grpc
+++ b/stage6-btpeer/02-chameleond/rootfs/etc/init.d/bluetooth_grpc
@@ -1,31 +1,52 @@
-#!/bin/sh
-# Copyright 2024 The ChromiumOS Authors
+#!/bin/bash
+# Copyright 2026 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
 ### BEGIN INIT INFO
-# Provides:          chameleond
+# Provides:          bluetooth_grpc
 # Required-Start:    $network $remote_fs
 # Required-Stop:     $network $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Start chameleond at boot time
-# Description:       Enable service provided by chameleond for remote
+# Short-Description: Start bluetooth_grpc and stop chameleond service before
+# Description:       Enable service provided by bluetooth_grpc for remote
 #                    controlling the Chameleon board.
 ### END INIT INFO
 
-DAEMON_NAME='chameleond'
-DAEMON="/etc/chromiumos/src/platform/chameleon/utils/run_chameleond_venv.sh"
+DAEMON_NAME='bluetooth_grpc'
+CHAMELEOND_SERVICE="chameleond"
+DAEMON="/etc/chromiumos/src/platform/chameleon/utils/run_bluetooth_grpc_venv.sh"
 DAEMON_USER='root'
 PIDFILE="/var/run/${DAEMON_NAME}.pid"
 LOGFILE="/var/log/${DAEMON_NAME}_init"
+
 RETRY_PERIOD=1
 
 is_already_running () {
     start-stop-daemon --stop --test --quiet --pidfile "${PIDFILE}"
 }
 
+is_chameleon_service_active() {
+    systemctl is-active --quiet "${CHAMELEOND_SERVICE}"
+    return $?
+}
+
 do_start () {
+    if is_chameleon_service_active; then
+        echo "Service '${CHAMELEOND_SERVICE}' is running."
+        echo "Stopping service '${CHAMELEOND_SERVICE}'..."
+
+        if systemctl stop "${CHAMELEOND_SERVICE}"; then
+            echo "Service '${CHAMELEOND_SERVICE}' stopped successfully."
+        else
+            echo "Error: Failed to stop service '${CHAMELEOND_SERVICE}'."
+        fi
+    else
+        echo "Service '${CHAMELEOND_SERVICE}' is not running."
+    fi
+
+
     if ! is_already_running; then
         start-stop-daemon --start --background --pidfile "${PIDFILE}" \
             --make-pidfile --user "${DAEMON_USER}" --chuid "${DAEMON_USER}" \
@@ -35,9 +56,6 @@ do_start () {
     else
         echo "${DAEMON_NAME} is already running."
     fi
-
-    # Unblock bluetooth if it was blocked
-    rfkill unblock bluetooth
 }
 
 do_stop () {
@@ -45,6 +63,10 @@ do_stop () {
         start-stop-daemon --stop --pidfile "${PIDFILE}" --retry "${RETRY_PERIOD}" --remove-pidfile
     else
         echo "${DAEMON_NAME} is already stopped"
+    fi
+
+    if ! is_chameleon_service_active; then
+        systemctl start "${CHAMELEOND_SERVICE}"
     fi
 }
 
